### ISSUE TITLE
将功能合并到现有 PDF 导出插件中的提案

### ISSUE THREAD

**Issue by sawhney17** [supery-chen/logseq-plugin-pdf-print#1]
您好，我是现有 [PDF 导出插件 for logseq](https://github.com/sawhney17/logseq-pdf-export/) 的作者，我真的很喜欢你所做的以及你为解决这个问题所采取的方法 问题。 所以我很好奇您是否想将此插件的功能与现有功能合并。 我会让你成为一个合作者，这意味着用户不必在两个插件之间进行选择，而是可以使用一个插件来完成所有事情。

如果您想继续，请告诉我。

我已经在 Github 中预览了它的外观。

没问题可以告诉我，不然我删了。
https://github.com/sawhney17/logseq-pdf-export/commit/c507de3000294a23031d734d013c11b8146a0372

¡Xie Xie!
<img width="410" alt="Screen Shot 2022-05-08 at 7 07 38 PM" src="https://user-images.githubusercontent.com/80150109/167302552-70f3f0b1-37ec-4546-b7b2-089de5a13efa.png">

**Comment by supery-chen** [comment]
没有问题😄
