### ISSUE TITLE
Bug Report：Latex "\sqrt{}" does not display correctly in PDF

### ISSUE THREAD

**Issue by skydtrtzmr** [supery-chen/logseq-plugin-pdf-print#2]
Hi！
Thanks for the awesome plugin！
I got a little problem. When there is a `\sqrt{}` expression (latex) :
![image](https://user-images.githubusercontent.com/45526359/183851864-3c17fe57-1908-4d19-93b4-0953735c5507.png)
The expected rendering is like that (as is shown in logseq)::
![image](https://user-images.githubusercontent.com/45526359/183851803-f97c0cfb-24f5-43e7-a71b-dac2eac1bfbe.png)
But when exported to pdf , the output seems wrong as seen in the image:
![image](https://user-images.githubusercontent.com/45526359/183851979-a7d18a7b-ab80-4bdb-b877-f205e6c7cd22.png)
I've tried different PDF readers and they turn out the same.

（Tried to submit an issue under 'logseq-pdf-export' before but have not received any response🤣and seems that this buggy behavior still exists）
https://github.com/sawhney17/logseq-pdf-export/issues/18#issue-1231911775

Could you please consider looking into this issue at your convenience?

Many thanks! 🎉

**Comment by supery-chen** [comment]
Hello, it's fixed now, you can upgrade to v0.0.3 to use it. Thanks for your feedback

![image](https://user-images.githubusercontent.com/54849153/183872975-6cab4d62-1df2-4be4-8c1b-20b5919a570c.png)

![image](https://user-images.githubusercontent.com/54849153/183873037-259187b4-d6d8-4c64-a748-ec20831cb340.png)

**Comment by skydtrtzmr** [comment]
Thanks so much😆
