### ISSUE TITLE
Highlights do not show up in print

### ISSUE THREAD

**Issue by antonba** [supery-chen/logseq-plugin-pdf-print#3]
Markdown highlights (which are denoted by enclosing text in "==") and presented in the Logseq editor as a yellow highlight do not show up.

e.g.

Regular text and some ==highlighted text==

This will show the "highlighted text" with a yellow background/highlight in the Logseq editor. This is standard markdown. Unfortunately in the printed version, the highlight is not shown.

**Comment by supery-chen** [comment]
Sorry for late response, it's fixed in v0.0.4😀
