### ISSUE TITLE
Unclear how to use. Broken?

### ISSUE THREAD

**Issue by sdasda7777** [supery-chen/logseq-plugin-pdf-print#5]
Hi, it's not clear to me how to use this extension.
I can't see the icon that is visible in the GIF.
Is it possible updates have broken it?

**Comment by supery-chen** [comment]
Please check if the printer service of the system is running

![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/75e6fb72-3fc9-42f7-8f35-b3ed6881dad1)

**Comment by sdasda7777** [comment]
I'm not sure there is one, I just want to print to PDF. Is that not what this extension does? I tried [sawhney17/logseq-pdf-export](https://github.com/sawhney17/logseq-pdf-export), and it technically works, but there is lot of bugs, so I'm looking for an alternative.

**Comment by supery-chen** [comment]
Run this command in PowerShell: `Get-Service -Name Spooler`
Check if the value of Status in the output is **Running**.

![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/033bda29-812e-4f3d-af1e-60012539c8f6)

---

The internal logic of this plugin is very simple, which is to invoke the `window.print()` method. Therefore, it relies on the operating system's spooler service.

**Comment by sdasda7777** [comment]
Hi, actually yeah, I can see the Spooler running.

![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/17746796/cab5038c-4242-48f8-8330-ec6d13f16f1f)

**Comment by supery-chen** [comment]
Update Logseq to the latest version and update this plugin to the latest version (v0.0.4), then try again.

If it still doesn't work, open the console (Ctrl + Shift + I), try again, check if there are any error messages in the console.

![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/84d142b7-3253-4893-8a16-aef5d3723cad)

**Comment by sdasda7777** [comment]
I seem to be up to date but I don't see any error in the console 😅

**Comment by supery-chen** [comment]
Can you run `window.print()` directly in Logseq's console?
![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/b312d6ab-600a-4344-b359-9dbe9e3ed3b3)

**Comment by sdasda7777** [comment]
Yeah, that works, it does show the system print dialog, saves to PDF (though the result is really ugly :/). The main issue seems to be that I just don't see the printer icon:

![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/17746796/d658bda5-d845-40e3-a9f0-80106fdd831a)

The PDF result:

![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/17746796/6bb8865b-e276-45df-84f3-29d418802374)

**Comment by supery-chen** [comment]
😂It seems like I misunderstood your question. Try the following steps
1. Click Plugins Icon
![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/10edf8fd-7bcd-48e9-a77a-ee62a12d491e)
2. Pin this plugin
![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/c8421afd-e9db-4dd5-a0f3-03684913a33f)
3. OK
![image](https://github.com/supery-chen/logseq-plugin-pdf-print/assets/54849153/cf64862c-d209-426f-ad5c-5c78e48211c4)

**Comment by sdasda7777** [comment]
Ah, I see 😂 Thanks and sorry for bothering 😄
